pattern = input()
print('-------------------------------')
print('| ', pattern[9], ' | ', pattern[10], ' | ', pattern[11], ' | ', pattern[12], ' | ', pattern[13], ' |')
print('-------------------------------')
print('| ', pattern[24], ' | ', pattern[1], ' | ', pattern[2], ' | ', pattern[3], ' | ', pattern[14], ' |')
print('-------------------------------')
print('| ', pattern[23], ' | ', pattern[8], ' | ', pattern[0], ' | ', pattern[4], ' | ', pattern[15], ' |')
print('-------------------------------')
print('| ', pattern[22], ' | ', pattern[7], ' | ', pattern[6], ' | ', pattern[5], ' | ', pattern[16], ' |')
print('-------------------------------')
print('| ', pattern[21], ' | ', pattern[20], ' | ', pattern[19], ' | ', pattern[18], ' | ', pattern[17], ' |')
print('-------------------------------')
input()